### ISSUE TITLE
Keyword arguments (kwargs) are ignored when plotting 

### ISSUE THREAD

**Issue by Up2nothing** [vyrjana/pyimpspec#10]
**Desktop (please complete the following information):**
- _pyimpspec_ version: 4.1.1
- Python version: 3.11.9
- OS: Windows

**Describe the bug**
When adding kwargs to plots they are not getting processed. 
For example in the plot_nyquist method kwargs are accepted but not unpacked and given to the plot or scatter methods
`def plot_nyquist(
    data: Union[DataSet, TestResult, FitResult, DRTResult],
    label: Optional[str] = None,
    colors: Optional[Dict[str, str]] = None,
    markers: Optional[Dict[str, str]] = None,
    line: bool = False,
    num_per_decade: int = 100,
    figure: Optional["Figure"] = None,  # noqa: F821
    legend: bool = True,
    axes: Optional[List["Axes"]] = None,  # noqa: F821
    adjust_axes: bool = True,
    colored_axes: bool = False,
    **kwargs,
) -> Tuple["Figure", List["Axes"]]:`
...
`    if line is True:
        axis.plot(
            x,
            y,
            color=color,
            linestyle="--",
            label=label if label != "" else None,
            **kwargs #  <--------------- MISSING!!!
        )
    else:
        axis.scatter(
            x,
            y,
            marker=marker,
            **_get_marker_color_args(marker, color),
            label=label if label != "" else None,
            **kwargs #  <--------------- MISSING!!!
        )`

**To Reproduce**
1. Using the API Load a DataSet
2. Once loaded call `plot_nyquist ` with e.g. alpha=0.5 as a kwarg
3.  No errors are produced, but the plot/scatter is **not** 50% transparent

**Expected behavior**
Show the plot with the additional kwargs (in this example in 50% transparency)

**Fix**
Pass the unpacked kwargs onto the scatter and plot methods.

**Comment by vyrjana** [comment]
The `**kwargs` are there in case there is a need to add more arguments to a function in the future without causing a change that breaks the backwards compatibility of the API and forcing the major version of pyimpspec to be incremented.

The plotting functions included with pyimpspec are primarily intended to help new users get started quickly. If you need different plots, then you can either create the starting point using pyimpspec's functions and modify the [Figure](https://matplotlib.org/stable/api/_as_gen/matplotlib.figure.Figure.html#matplotlib-figure-figure) and [Axes](https://matplotlib.org/stable/api/_as_gen/matplotlib.axes.Axes.html#matplotlib-axes-axes) instances, or start from scratch and plot the data returned by the methods of the various classes such as `DataSet.get_impedances()`.

**Comment by Up2nothing** [comment]
Hi, thanks for the fast reply and explanation. What you say makes total sense and I will adjust my code approprietly!
