### ISSUE TITLE
_calculate_residuals function calculates wrong values

### ISSUE THREAD

**Issue by michaelgr22** [vyrjana/pyimpspec#4]
**Desktop (please complete the following information):**
- _pyimpspec_ version: 4.1.0
- Python version: 3.11.4
- OS: Windows

**Describe the bug**
current implementation of `pyimpspec.analysis.utility.residuals`:
```python
def _calculate_residuals(
    Z_exp: ComplexImpedances,
    Z_fit: ComplexImpedances,
) -> ComplexResiduals:
    residuals: ComplexResiduals = empty(Z_exp.shape, dtype=ComplexResidual)
    residuals.real = (Z_exp.real - Z_fit.real) / abs(Z_exp)
    residuals.imag = (Z_exp.imag - Z_fit.imag) / abs(Z_exp)
    return residuals
```

according to equation [1] in `B.A. Boukamp, 1995, J. Electrochem.` the denominator is

>  the vector length (absolute value) of the _**modeling function**_

so the equations should be:
```python
residuals.real = (Z_exp.real - Z_fit.real) / abs(Z_fit)
residuals.imag = (Z_exp.imag - Z_fit.imag) / abs(Z_fit)
```

**Comment by vyrjana** [comment]
Hi!

The relative residuals are calculated according to equations 15 and 16 in [Schönleber et al. (2014)](https://doi.org/10.1016/j.electacta.2014.01.034). I have added this information as a comment in the relevant source file in the private development branch for the next update. The change will eventually show up in the main public branch.

Always good to have another pair of eyes looking over the source code in case something was overlooked. I appreciate you taking the time to do so!
